services:
  - type: web
    name: medical-lab-parser-server
    env: node
    nodeVersion: 18.15.11
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true 